/* record/Descriptions.H: part of meabench, an MEA recording and analysis tool
** Copyright (C) 2000-2002  Daniel Wagenaar (wagenaar@caltech.edu)
**
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 2 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

// Descriptions.H

#ifndef RECDESCRIPTIONS_H

#define RECDESCRIPTIONS_H

#include <base/Description.H>

#define dRUNLENGTH "Run length"
#define dRAWSAMFREQ "Raw sample freq"
#define dGAIN "Gain"
#define dAUXGAIN "Aux gain"
#define dTRIGGERED "Triggered"
#define dTRIGWIN "Trigger window"
#define dPRETRIG "Pre trigger time"
#define dPOSTTRIG "Post trigger time"
#define dNTRIG "Number of triggers"
#define dHWERR "  Hardware errors"
#define dOVERRUN "  Buffer overruns"
#define dHARDWARE "Hardware"
#define dSPKDET "Spike detector"
#define dTHRESH "Threshold"
#define dNSPIKES "Number of spikes"
#define dDATAFN "Data filename"
#define dCREAPROG "Creating program"
#define dCREAUSER "Creating user"
#define dSTART "Start date"
#define dEND "End date"
#define dDATE "Date"
#define dCOMMENTS "Comments"
#define dDATATYP "Data type"
#define dIMMSRC "Immediate source"
#define dRUNSTART "Run start timestamp"
#define dBUFUSE "Buffer use percentages"
#define dSPKTHRESH "Threshold values"
#define dSPKUNIT "Threshold unit"
#define dTERMINATION "Recording terminated by"
#define dDIGIZERO "Digital zero"
#define dDIGIMIN "Digital min. rail"
#define dDIGIMAX "Digital max. rail"
#define dDIGIRANGE "Nominal half range"
#define dRMSPERIOD "RMS Period"
#define dPARACCUM "Misc. parameters"
#define dYES "Yes"
#define dNO "No"

#endif
